spring.datasource.url=jdbc:mysql://database-1.cpggk8os8ndt.us-east-2.rds.amazonaws.com:3306/n44db?useSSL=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=JmQCJ9yayxMZaesEGOrC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false